### ISSUE TITLE
Tiny symbols in SWCCG template

### ISSUE THREAD

**Issue by papatkins** [usmcgeek/meccg#1]
First, thanks for creating such a fantastic tool. Very fun to play with.

When inserting symbols into SWCCG template text box, they shrink to an incredibly small size. An upscaled versions of the ds pilot logo (388x380), also shrank to the same incredibly small size as the default symbol. Symbols appear the proper size when dropped into the right-hand boxes (e.g. standard 'pilot' symbol placement).

In the MECCG templates, symbols appear properly scaled in the text box, so I assume this is a SWCCG template specific issue. I was unable to determine why this was occurring.

**Comment by usmcgeek** [comment]
Thanks - I found it and got it correct, they scale now properly.
